[project]
authors = ["Nicklas <gitnicklas@pm.me>"]
channels = ["robostack-staging", "conda-forge"]
description = "Walk like your feet are kissing the earth."
name = "tpc"
platforms = ["linux-64"]
version = "0.2.0"

[pypi-dependencies]
tpc = { path = ".", editable = true }
# tpc_test = { path = "tests", editable = true }
# gymnasium = { version = "*", extras = ["classic-control"] }

[tasks]

[dependencies]
python = "=3.10"
gymnasium = "*"
pygame = "*"
numpy = "*"
loguru = "*"
termcolor = "*"
matplotlib = "*"
simple-pid = "*"
ros-humble-desktop = "*"
colcon-common-extensions = "*"
setuptools = "*"
pytz = "*"
imageio = ">=2.36.0,<3"
imageio-ffmpeg = ">=0.5.1,<0.6"
opencv = ">=4.6.0,<5"

[feature.test.tasks]
test = "pytest"
# colcon-common-extensions = "*"
# gymnasium = { version = "*", extras = ["classic-control"] }
