[project]
authors = [
  "Nicklas <gitnicklas@pm.me>",
  "Sasanka Kuruppuarachchi"
]
channels = ["conda-forge"]
description = "Walk like your feet are kissing the earth."
name = "tpc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.1.1,<3"
hydra-core = ">=1.3.2,<2"
python = ">=3.12.6,<4"
