[project]
authors = [{name = "Nicklas", email = "gitnicklas@pm.me"}]
description = "Walk like your feet are kissing the earth."
dependencies = []
name = "tpc"
requires-python = ">= 3.10"
version = "0.2.0"

# [build-system]
# build-backend = "hatchling.build"
# requires = ["hatchling"]

